#!/usr/bin/env node
// Regenerates RULES.md from the rule definitions and the two sample reports in examples/.
// CI runs this and fails if RULES.md is out of date.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadAdvisories } from '../src/advisories.mjs';
import { runCheck } from '../src/check.mjs';
import { renderMarkdown } from '../src/report.mjs';
import { RULES } from '../src/rules.mjs';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const rel = (p) => path.join(ROOT, p);

const DROPPED = [
  ['Agent tool queries not scoped to the signed-in user (OWASP LLM01)', 'Whether a query is limited to the right customer depends on where the id comes from, which a static check cannot prove. It is part of the manual review.'],
  ['Secret compared with === instead of a constant-time comparison', 'Too noisy when judged from code text alone.'],
  ['Missing dead-letter path', 'Only detectable through naming conventions. The observable part is covered by HTTP-NO-RETRY and ERRORS-SWALLOWED.'],
  ['Retry settings on every integration node (Slack, Gmail, CRM…)', 'Produced more noise than signal in testing; HTTP Request nodes are checked because they are where custom APIs are called.'],
  ['Rate limiting, instance settings, user roles, credential sharing', 'Not part of a workflow export. Checked in the instance audit instead.'],
];

function rulesMd() {
  const out = ['# Rules', '', '<!-- Generated by scripts/build-samples.mjs from src/rules.mjs. Do not edit by hand. -->', ''];
  out.push('| Rule | Default severity | Effort | What it catches |', '|---|---|---|---|');
  for (const r of RULES) out.push(`| [\`${r.id}\`](#${r.id.toLowerCase()}) | ${r.severity} | ${r.effort} | ${r.title} |`);
  out.push('');
  out.push('Severity can be raised or lowered per finding: for example an unauthenticated webhook is high when it reaches a database or an external call and medium when it does not.', '');
  for (const r of RULES) {
    out.push(`## ${r.id}`, '', `**${r.title}** (default severity: ${r.severity}${r.scope === 'run' ? ', checked once per run' : ''})`, '');
    out.push(`**Why it matters.** ${r.why}`, '', `**How to fix.** ${r.fix}`, '');
    if (r.refs?.length) out.push(`**References.** ${r.refs.map((u) => `<${u}>`).join(', ')}`, '');
  }
  out.push('## Considered and left out', '', 'These were considered and deliberately not implemented as automatic rules:', '');
  for (const [what, why] of DROPPED) out.push(`- **${what}.** ${why}`);
  out.push('');
  return out.join('\n');
}

const check = process.argv.includes('--check');
const rules = rulesMd();
if (check) {
  if (fs.readFileSync(rel('RULES.md'), 'utf8') !== rules) {
    console.error('RULES.md is out of date. Run "npm run samples" and commit the result.');
    process.exit(1);
  }
  console.log('RULES.md is up to date.');
  process.exit(0);
}

fs.writeFileSync(rel('RULES.md'), rules);

const advisoryData = loadAdvisories();
const date = (advisoryData.generatedAt || new Date().toISOString()).slice(0, 10);
const ignore = JSON.parse(fs.readFileSync(rel('fixtures/portfolio/.prodcheck-ignore.json'), 'utf8')).ignore;

// The portfolio before its RFQ endpoints got authentication (fixed in n8n-portfolio PR #5).
const beforeFiles = fs.readdirSync(rel('fixtures/portfolio-before-fix')).filter((f) => f.endsWith('.json'));
const beforeTargets = fs.readdirSync(rel('fixtures/portfolio'))
  .filter((f) => f.endsWith('.json') && !beforeFiles.includes(f))
  .map((f) => rel(`fixtures/portfolio/${f}`))
  .concat(beforeFiles.map((f) => rel(`fixtures/portfolio-before-fix/${f}`)));
const portfolio = runCheck({ targets: beforeTargets, n8nVersion: '2.40.5', ignore, advisoryData });
const after = runCheck({ targets: [rel('fixtures/portfolio')], n8nVersion: '2.40.5', ignore, advisoryData });
fs.writeFileSync(rel('examples/sample-report-portfolio.md'), renderMarkdown(portfolio, {
  base: rel('fixtures'),
  title: 'Sample report: the author\'s own portfolio',
  subject: `[n8n-portfolio](https://github.com/nikolaRadosavljevic95/n8n-portfolio), 16 workflows, as they were on 2026-09-24, with the reviewed exceptions in fixtures/portfolio/.prodcheck-ignore.json. The four findings below were fixed in [n8n-portfolio#5](https://github.com/nikolaRadosavljevic95/n8n-portfolio/pull/5); the same check on the fixed workflows reports ${after.findings.length} findings.`,
  date,
}));

const synthetic = runCheck({ targets: [rel('fixtures/bad')], n8nVersion: '1.120.0', advisoryData });
fs.writeFileSync(rel('examples/sample-report-synthetic.md'), renderMarkdown(synthetic, {
  base: rel('fixtures'),
  title: 'Sample report: synthetic example',
  subject: 'Synthetic workflows written to trigger every rule (fixtures/bad), checked as if they ran on n8n 1.120.0. Not a real client.',
  date,
}));

console.log('Wrote RULES.md, examples/sample-report-portfolio.md, examples/sample-report-synthetic.md');
